version: '3.8'

services:
  fpm:
    container_name: ${PROJECT_NAME}_fpm
    build:
      context: ../../
      dockerfile: ./docker/dev/fpm/Dockerfile
    depends_on:
      - db
    volumes:
      - ../../:/code
    working_dir: /code/src
    restart: "no"
    entrypoint: /entrypoint.sh
    command: php-fpm

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:1.27.0
    depends_on:
      - fpm
    ports:
      - "8080:80"
    volumes:
      - ../../src/public:/code/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: "no"
    networks:
      - default

  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${PROJECT_NAME}
      - MYSQL_ROOT_PASSWORD=mypass
    ports:
      - "33240:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: "no"

networks:
  default:
    driver: bridge
